spring:
  application:
    name: lwx-magic-code-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lwx_magic_code
    username: root
    password: 2909314910
  profiles:
    active: local
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # redis
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      ttl: 3600


server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lwx.lwxmagiccodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn